#!/usr/bin/env bash

## Export in your environment the configuration variables:
# SPACE_ID='<space_id>'
# CMA_TOKEN='<cma_token>'

## Dependencies:
## - sh
## - curl
## - grep

contenttype_put() {
  local typename="$1"
  local filename="$2"
  local response

  response="$(mktemp)"
  curl --silent \
    --include \
    --request PUT \
    --header "Authorization: Bearer ${CMA_TOKEN}" \
    --header 'Content-Type: application/vnd.contentful.management.v1+json' \
    --data-binary @"${filename}" \
    "https://api.contentful.com/spaces/${SPACE_ID}/content_types/${typename}" > "$response"
  cat "$response"
  status_code_must_be "$response" 201
}

contenttype_delete() {
  local typename="$1"
  local response

  response="$(mktemp)"
  curl --silent \
    --include \
    --request DELETE \
    --header "Authorization: Bearer ${CMA_TOKEN}" \
    --header 'Content-Type: application/vnd.contentful.management.v1+json' \
    "https://api.contentful.com/spaces/${SPACE_ID}/content_types/${typename}" > "$response"
  cat "$response"
  status_code_must_be "$response" 204
}

contenttype_activate() {
  local typename="$1"
  local response

  response="$(mktemp)"
  curl --silent \
    --include \
    --request PUT \
    --header "Authorization: Bearer ${CMA_TOKEN}" \
    --header 'X-Contentful-Version: 1' \
    "https://api.contentful.com/spaces/${SPACE_ID}/content_types/${typename}/published" > "$response"
  cat "$response"
  status_code_must_be "$response" 200
}

content_get() {
  local entry_id="$1"
  local response

  response="$(mktemp)"
  curl --silent \
    --include \
    --request GET \
    --header "Authorization: Bearer ${CMA_TOKEN}" \
    "https://api.contentful.com/spaces/${SPACE_ID}/entries/${entry_id}" > "$response"
  cat "$response"
  status_code_must_be "$response" 200
}

content_post() {
  local typename="$1"
  local filename="$2"
  local response

  response="$(mktemp)"
  curl --silent \
    --include \
    --request POST \
    --header "Authorization: Bearer ${CMA_TOKEN}" \
    --header 'Content-Type: application/vnd.contentful.management.v1+json' \
    --header "X-Contentful-Content-Type: ${typename}" \
    --data-binary @"${filename}" \
    "https://api.contentful.com/spaces/${SPACE_ID}/entries" > "$response"
  cat "$response"
  status_code_must_be "$response" 201
}

status_code_must_be() {
  local response_file="$1"
  local expected_code="$2"

  if [[ $(status_code "$response") != "${expected_code}" ]]; then exit 1; fi
}

status_code() {
  response_file="$1"

  if [[ "$(awk -F " " '{print $2}' <(sed '1q;d' "$response_file"))" == '100' ]]; then
    awk -F " " '{print $2}' <(sed '3q;d' "$response_file")
  else
    awk -F " " '{print $2}' <(sed '1q;d' "$response_file")
  fi
}

unrecognised_command() {
  echo "Command not found: '${1}'."
  exit 1
}

handle_contenttype() {
  case $1 in
    put)
      shift
      contenttype_put "$@"
      ;;
    activate)
      shift
      contenttype_activate "$@"
      ;;
    delete)
      shift
      contenttype_delete "$@"
      ;;
    *)
      unrecognised_command "$@"
  esac
}

handle_content() {
  case $1 in
    get)
      shift
      content_get "$@"
      ;;
    post)
      shift
      content_post "$@"
      ;;
    *)
      unrecognised_command "$@"
  esac
}

case $1 in
  content-type|ct)
    shift
    handle_contenttype "$@"
    ;;
  content|c)
    shift
    handle_content "$@"
    ;;
  *)
    unrecognised_command "$@"
esac
